apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: wpcm
              key: db
        - name: WORDPRESS_DB_NAME
          valueFrom: 
            configMapKeyRef:
              name: wpcm
              key: dbname
        - name: WORDPRESS_DB_USER
          valueFrom: 
            secretKeyRef:
              name: wpsecret
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: wpsecret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
