apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: busybox
      image: busybox
      volumeMounts:
      - name: pvc
        mountPath: "/tmp/data"
      command: ["sleep", "3600"]
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: mypvc
