apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: harbor.nsx.techlab.netone.co.jp/handson/mysql:5.7.43
        name: mysql
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: wordpress-configmap
              key: dbname
        - name: MYSQL_USER
          valueFrom: 
            secretKeyRef:
              name: wordpress-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: wordpress-secret
              key: password
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
          subPath: mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: unity-k8s
      resources:
        requests:
          storage: 2Gi
