apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: wordpress-configmap
              key: db
        - name: WORDPRESS_DB_NAME
          valueFrom: 
            configMapKeyRef:
              name: wordpress-configmap
              key: dbname
        - name: WORDPRESS_DB_USER
          valueFrom: 
            secretKeyRef:
              name: wordpress-secret
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: wordpress-secret
              key: password
